@host = 127.0.0.1:4221

GET http://{{host}}
Content-Type: application/json

{"test":123}

####

curl -v -X GET http://{{host}}/echo/humpty-humpty

####

curl -v -X GET http://localhost:4221/user-agent -H "User-Agent: donkey/Horsey-vanilla"